spring:
  application:
    name: discovery-server1

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    
debug: false

logging:
  level:
    root: INFO
    com.wcbeh: TRACE
#    org.hibernate.sql: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG