spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wcbeh_db?useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: password
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: crud-service
      
server:
  port: 7001
        
debug: false

logging:
  level:
    root: INFO
    com.wcbeh: TRACE
#    org.hibernate.sql: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG